- src/app/app.component.ts
- src/app/pages/tabs-page/tabs-page.ts
fixed #1 by copying the parts that were doing it right
> Update menu and tab on login/logout

- .github/workflows/CI.yml
- src/app/pages/map/map.html
- src/app/pages/speaker-list/speaker-list.html
- src/app/pages/speaker-list/speaker-list.ts
- src/app/providers/conference-data.ts
- Paginate rendering
- Lazy load speaker images
- asyncify
- add loader
closes #11
> Overhaul speaker loading

- src/app/pages/schedule-filter/schedule-filter.html
> fix: reset selects all tracks

- src/app/pages/schedule/schedule.html
- src/app/pages/schedule/schedule.ts
- src/app/pages/speaker-list/speaker-list.html
- src/app/pages/speaker-list/speaker-list.ts
> fix: focus search box once button pressed

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/assets/capacitor.config.json
- android/app/src/main/res/values/strings.xml
- capacitor.config.ts
- ios/App/App.xcodeproj/project.pbxproj
- ios/App/App/Info.plist
- ios/App/App/capacitor.config.json
- src/app/app.module.ts
- src/app/autofill.directive.spec.ts
- src/app/autofill.directive.ts
- src/app/pages/login/login.html
- src/app/providers/user-data.ts
- Determine features based on API response
- Allow auto-fill by password manager
- Associate the app with us.pycon.org for password manager auto-fill hinting
> Login finalization

- src/app/app.component.ts
- src/app/pages/schedule/schedule.ts
- src/app/pages/speaker-list/speaker-list.html
- src/app/providers/conference-data.ts
- src/app/providers/pycon-api.ts
- src/app/providers/user-data.ts
> Favorites persistence

- angular.json
- src/app/app-routing.module.ts
- src/app/app.component.ts
- src/app/pages/about/about.html
- src/app/pages/about/about.ts
- src/app/pages/schedule/schedule.html
- src/app/pages/speaker-list/speaker-list.html
- src/app/pages/sponsors/sponsors-routing.module.ts
- src/app/pages/sponsors/sponsors.module.ts
- src/app/pages/sponsors/sponsors.page.html
- src/app/pages/sponsors/sponsors.page.spec.ts
- src/app/pages/sponsors/sponsors.page.ts
- src/app/pages/tabs-page/tabs-page-routing.module.ts
- src/app/providers/conference-data.ts
- src/app/providers/user-data.ts
- About page closes #27 
- Lots of schedule updates to present non "presentation" sessions more clearly
- Fix timezone bug, supersedes #31 
- Add Sponsors view
- Minor fixups across other pages.
> Big updates

- src/app/pages/schedule/schedule.html
- src/app/pages/schedule/schedule.ts
- src/app/providers/conference-data.ts
- src/app/providers/user-data.ts
lil fixes for schedule view around favorites.
still getting some likely async induced weirdness when adding/removing as they don't render immediately in the other tab yet. :/
> Schedule and favorites

- src/app/app.component.html
- src/app/app.component.ts
- src/app/providers/user-data.ts
Implements theme persistence from #35
Signed-off-by: Mike Fiedler <miketheman@gmail.com>
> feat: persist theme choice to storage

- src/app/app.component.html
- src/app/app.component.ts
- src/app/pages/about-pycon/about-pycon.page.html
> Loren Request: Add 'US' to the side menu and page title

- src/app/pages/schedule/schedule.scss
Prevent extending beyond the viewable area on smaller screens.
Fixes #32
https://user-images.githubusercontent.com/529516/233516612-82148aca-ec17-4867-aed0-33b9045c9ac8.mov
> fix: automatically adjust button widths

- src/app/app.component.ts
| Before | After |
|--------|--------|
| ![Simulator Screenshot - iPhone 14 Pro - 2023-04-21 at 18 25 47](https://user-images.githubusercontent.com/714118/233743936-6d594cb7-fa71-4734-98bd-057606767fbd.png) | ![Simulator Screenshot - iPhone 14 Pro - 2023-04-21 at 18 27 05](https://user-images.githubusercontent.com/714118/233743944-ea93fd9c-9a04-4199-b9e3-af2c198268ed.png) |
> Unhide status bar so time is visible

- package-lock.json
- package.json
- patches/@capacitor-mlkit+barcode-scanning+7.1.0.patch
Improves stability of opening/closing barcode scanner view on iOS.
Can be reverted once https://github.com/capawesome-team/capacitor-mlkit/pull/255 is released.
> apply patch to @capacitor-mlkit/barcode-scanning awaiting release

- android/app/capacitor.build.gradle
- android/app/src/main/assets/capacitor.plugins.json
- android/capacitor.settings.gradle
- ios/App/Podfile
- package-lock.json
- package.json
- src/app/pages/door-check/door-check.page.ts
- src/app/pages/map/map.html
- src/app/pages/map/map.ts
- src/app/pages/t-shirt-redemption/t-shirt-redemption.page.html
- src/app/pages/t-shirt-redemption/t-shirt-redemption.page.ts
- src/app/providers/pycon-api.ts
improve reliability/durability of lead-retrieval scanner
- check for network before attempting syncs
- store syncs that fail > 10 times into local storage
make door-check more reliable, notify pycon db of door scans
improve user-experience on swag-redemption tooling
> Improvements for scanning apps

- README.md
- Use the real repo link
- Remove ionic example images
> chore: small readme updates for getting started

- README.md
- package-lock.json
- package.json
while reviewing https://github.com/psf/pycon-us-mobile/pull/83 i noticed that the dev/prod separation wasn't strong enough in helper capsync
> document prod build a bit better

- .github/ISSUE_TEMPLATE.md
This means instead of issues looking like:
---
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/
---
They look like:
---
**I'm submitting a ...**  (check one with "x")
---
> Issue template: Use Markdown checklist formatting

- Makefile
- README.md
- angular.json
- src/app/pages/about-pycon/about-pycon.page.html
- src/app/pages/about-pycon/about-pycon.page.ts
- src/app/pages/login/login.ts
- src/app/providers/conference-data.ts
- src/app/providers/pycon-api.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
Uses local URLs when not in prod environment
> feat(dev): use local urls when in development

- src/app/pages/map/map.ts
https://github.com/psf/pycon-us-mobile/commit/f409f0dc7ac009da0603f62f1fb3fa59fbf7f3dd#diff-3d9f46fb14bc8f19a382532868e34d31e8085d1c80291448d0bbb4110b42d9aaL126-R133
> revert boneheaded attempt to simplify logic in camera permissions check

- src/app/pages/t-shirt-redemption/t-shirt-redemption.page.ts
Reverts psf/pycon-us-mobile#100, didn't realize we were debugging version 3.1.0 🤦🏼
> Revert "fix: swag scan cancel button acting naughty"

- src/app/providers/conference-data.ts
> fix: add imageUrl back

- src/app/pages/schedule/schedule.ts
Reverts psf/pycon-us-mobile#105
> Revert "Reload schedule if we asynchronously change the day"
